// authentication flow ...
// authentication flow ...
// authentication flow ...
///////////////////////////////////////

// coding ...
// coding ...
// coding ...
///////////////////////////////////////
// added some feature for developing this
// what i the helllll

// ok
// working .. .
// finished

// start working in user-profile-not-shown bug
// coding ..
// coding ..
// finished

// start working in how user is so stupid
// coding...
// coding...
// coding...
// finished
